---
title: "CMI_ABCD_JIVE"
author: "Lucinda Sisk"
date: "1/12/2020"
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, include=FALSE, tidy=TRUE}

list.of.packages <- c("tidyverse", "psycho", "r.jive", "here")

load_pck <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

load_pck(list.of.packages)

path <- here()
home <- "/Users/lucindasisk/Box/LS_Folders/CMI_ABCD" #paste(path,'../../../Box/LS_Folders/CMI_ABCD', sep='/')
plots <- paste(home,'R.JIVE/plots', sep='/')

#Read in JIVE data
brain_data <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/CMI_Collab_Brain_Measures_1.4.19.csv')
pheno_data <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/phenoData_analysis_08062019.csv')

#Read in raw trauma endorsements
abcd_trauma <- read_tsv('/Users/lucindasisk/Desktop/ABCD/ABCDstudyNDA-2.0/abcd_ptsd01.txt', col_names=TRUE) %>%
  filter(eventname=="baseline_year_1_arm_1")

#Read in Sample 1 Subids
samp1_ids <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/CMI_ABCD_Sample1_IDs.csv', col_names=TRUE)

#Read in Sample 2 Subids 
samp2_ids <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/CMI_ABCD_Sample2_IDs.csv', col_names=TRUE)

```


```{r, echo=FALSE, include=FALSE, tidy=TRUE}
#Read in last 50 sub pheno
disc_pheno_data <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/ABCD_metrics/discovery_addition_pheno_1.14.20.csv', col_names=TRUE)

rep_pheno_data <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/ABCD_metrics/replicate_pheno_1.14.20.csv', col_names=TRUE)

```
### Score ABCD Trauma Data

```{r, tidy=TRUE}

#Score abcd trauma data
abcd_trauma_scored <- abcd_trauma %>%
  #Ensure conversion to data frame
  data.frame() %>%
  #Select columns of interest
  select(src_subject_id, ksads_ptsd_raw_754_p:ksads_ptsd_raw_770_p) %>%
  #Convert score columns to numeric type for summing
  type_convert(col_types = cols(ksads_ptsd_raw_754_p ="i",
                                ksads_ptsd_raw_755_p ="i",
                                ksads_ptsd_raw_756_p ="i",
                                ksads_ptsd_raw_757_p ="i",
                                ksads_ptsd_raw_758_p ="i",
                                ksads_ptsd_raw_759_p ="i",
                                ksads_ptsd_raw_760_p ="i",
                                ksads_ptsd_raw_761_p ="i",
                                ksads_ptsd_raw_762_p ="i",
                                ksads_ptsd_raw_763_p ="i",
                                ksads_ptsd_raw_764_p ="i",
                                ksads_ptsd_raw_765_p ="i",
                                ksads_ptsd_raw_766_p ="i",
                                ksads_ptsd_raw_767_p ="i",
                                ksads_ptsd_raw_768_p ="i",
                                ksads_ptsd_raw_769_p ="i",
                                ksads_ptsd_raw_770_p  = "i")) %>%
  #Create summed scores of trauma exposures
  mutate(trauma_num = rowSums(.[2:18])) %>%
  #Add new column with cleaned subid
  mutate("subjectkey" = str_remove(src_subject_id, "[_]")) %>% 
  #Add new col with scaled trauma data
  mutate("trauma_num" = scale(trauma_num)) %>% 
  #Drop NAs
  na.omit() 

#Scale trauma data in phenotypic dataset
pheno_data_scaled <- pheno_data %>% 
  mutate("trauma_num" = scale(trauma_num))

#Get column names of original data
pheno_data_cols <- colnames(pheno_data)

#Add scaled trauma data to phenotypic dataset (sample 1)
final_sample1 <- left_join(samp1_ids, abcd_trauma_scored, by = "subjectkey") %>% 
  select("subjectkey", "trauma_num") %>% 
  right_join(disc_pheno_data, by = c('subjectkey'="subjectkey")) %>% 
  select(pheno_data_cols) %>% 
  rbind(., pheno_data_scaled)

#Add scaled trauma data to phenotypica dataset (sample 2)
final_sample2 <- left_join(samp2_ids, abcd_trauma_scored, by = "subjectkey") %>% 
  select("subjectkey", "trauma_num") %>% 
  left_join(rep_pheno_data, by = c('subjectkey'="subjectkey")) %>% 
  select(pheno_data_cols)

```


```{r, tidy=TRUE}

#Write final sample1 and sample2 data to CSV
write_csv(final_sample1, paste(home, 'final_pheno_sample1_LS_1.15.19.csv', sep='/'))
write_csv(final_sample2, paste(home, 'final_pheno_sample2_LS_1.15.19.csv', sep='/'))

```

```{r, tidy=TRUE}
#Drop ID columns; drop all columns that sum to 0
brain_datano0 <- brain_data %>%
    select(-c('subid')) %>%
    select_if(colSums(.) > 0 ) %>%
    mutate("subid" = brain_data$subid)

#Standardize (scale and center) phenotypic data
pheno_data_scaled <- pheno_data %>%
    standardize() %>%
    rename("subid" = "subjectkey")

#Merge data frames to ensure they are in same order
combined_df <- right_join(pheno_data_scaled, brain_data_scaled, by = 'subid')

###############################################################################################

new_pheno <- combined_df %>%
    select('interview_age','cbcl_scr_syn_anxdep_t':'trauma_num') %>%
    mutate_all(funs(replace_na(., 0))) #Replace NAs with 0's --> check if OK

new_brain <- combined_df %>%
    select('area_L_1':'thickness_R_20442') %>%
    mutate_all(funs(replace_na(., 0))) #Replace NAs with 0's --> check if OK



#Convert non-continuous data to factors
# new_pheno$sex <- as.factor(new_pheno$sex)
# new_pheno$site_id_l <- as.factor(new_pheno$site_id_l)

#Transpose so IDs are columns
new_pheno_mat <- t(new_pheno) 
new_brain_mat <- t(new_brain)
```
## Prepare matrices, run jive

* Data requirements: A list of two or more linked data matrices on which to perform the JIVE decomposition. These matrices must have the same column dimension, which is assumed to be common.
```{r, tidy=TRUE}
#data1 <- list(area_data, myelin_data, stress_data, thick_data, cbcl_data) 
data <- list(new_pheno_mat, new_pheno_mat)
```

```{r, tidy=TRUE}
#Run JIVE analysis

#Estimate JIVE ranks based on permutation testing (best validated)
#Row-orthogonality enforced between the joint and individual estimates and also between each individual estimate.
#Compute ranks
(try(cmi_jive_result <- jive(data, scale = TRUE)))

#Get Results
result_joint_rank <- cmi_jive_result$rankJ
result_individ_rank <- cmi_jive_result$rankA

#Plot variance explained by individual and joint ranks, and noise
(try(cmi_jive_var <- showVarExplained(cmi_jive_result, col = c("#811c4e", "#fdb663", "#37486d"))))

#Plot heatmaps of results
(try(cmi_jive_heatmaps <- showHeatmaps(cmi_jive_result, order_by = 0, show_all = TRUE)))

#Plot PCA 
try(cmi_jive_pca <- showPCA(cmi_jive_result, n_joint = 1, n_indiv = c(1,1), Colors = c("#811c4e", "#fdb663")))
#No clustering efects apparent

```

## Results:
* Joint Rank: `r result_joint_rank`
* Individual Ranks: `r result_individ_rank`


$\\$


```{r, tidy=TRUE}
# ##Save images
# #Save variance images
# png(paste(here, "/CMI_JIVE_VarExplained.png", sep=''),height=300,width=450)
# cmi_jive_var
# dev.off()
# 
# #Save heatmaps
# png(paste(here, "/CMI_JIVE_Heatmaps.png", sep=''),height=465,width=705)
# cmi_jive_heatmaps
# dev.off()
```




