---
title: "CMI_ABCD_JIVE"
author: "Lucinda Sisk"
date: "1/12/2020"
output:
  pdf_document: default
  html_document: default
---

```{r set_libraries, echo=FALSE, include=FALSE, tidy=TRUE}

require(tidyverse)
require(r.jive)
require(readxl)
require(dplyr)
library(Spectrum)
library(plot3D)


```

```{r read_in_files, tidy=TRUE, echo=FALSE}
not_all_na <- function(x) any(!is.na(x))

#results <- '/gpfs/milgram/project/gee_dylan/lms233/CMI_ABCD/FinalData'
results <- '/Users/lucindasisk/Box/LS_Folders/CANDLab/Projects/CMI_Structural_ABCD/Data/Final_3.12.20'

#Read in JIVE data
pheno_cols = c('subid','crpbi_y_ss_parent',	'crpbi_y_ss_caregiver',	'trauma_num',	'fam_hist',	'pmq_y_ss_mean',	'srpf_y_ss_ses',	'nsc_p_ss_mean_3_items',	'fes_p_ss_fc')

pheno_data1 <- read_csv(paste(results,'discovery_zscore_clinical.csv', sep='/'), 
                        col_names = pheno_cols) %>% 
  na_if(0) %>% 
  select_if(not_all_na) %>% 
  replace_na(list('NA' = 0, 'Inf'= 0))
#Drop first row from sample 1
pheno_data1 <- pheno_data1[-c(1), ]

pheno_data2 <- read_csv(paste(results,'replication_zscore_clinical.csv', sep='/'), 
                        col_names = pheno_cols) %>% 
  na_if(0) %>% 
  select_if(not_all_na) %>% 
  replace_na(list('NA' = 0, 'Inf'= 0))
#Drop first row from sample 2
pheno_data2 <- pheno_data2[-c(1), ]

samp1_ids <- select(pheno_data1, subid)
samp2_ids <- select(pheno_data2, subid)

#Read in myelin and thickess

myelin_data_samp1 <- read_csv(paste(results,'discovery_zscore_myelin.csv', sep='/'), col_names = TRUE) %>% 
  rename("subid" = CASE_FN_disc)

thick_data_samp1 <- read_csv(paste(results, 'discovery_zscore_thickness.csv', sep='/'), col_names = TRUE)%>% 
  rename("subid" = CASE_FN_disc)

#Get column names from sample1, apply to sample2

myelin_data_samp2 <- read_csv(paste(results,'replication_zscore_myelin.csv', sep='/'), col_names = TRUE) %>% 
  rename("subid" = CASE_FN_repl)

thick_data_samp2 <- read_csv(paste(results, 'replication_zscore_thickness.csv', sep='/'), col_names = TRUE)%>% 
  rename("subid" = CASE_FN_repl)

#Read in subtype membership data

disc_k2 <- read_excel(paste(results,'subtype_membership.xlsx', sep='/'), sheet=1,
                     col_names=FALSE) %>% 
  rename("subid" = ...1, "group" = ...2)

repl_k2 <- read_excel(paste(results,'subtype_membership.xlsx', sep='/'), sheet=2,
                     col_names=FALSE) %>% 
  rename("subid" = ...1, "group" = ...2)

disc_k5 <- read_excel(paste(results,'subtype_membership.xlsx', sep='/'), sheet=3,
                     col_names=FALSE) %>% 
  rename("subid" = ...1, "group" = ...2)

repl_k5 <- read_excel(paste(results,'subtype_membership.xlsx', sep='/'), sheet=4,
                     col_names=FALSE)    %>% 
  rename("subid" = ...1, "group" = ...2)

```

```{r select_data, tidy=TRUE}

not_all_na <- function(x) any(!is.na(x))

#Drop ID columns; drop all columns that sum to 0
myelin_data_samp1 <- myelin_data_samp1 %>%
  na_if(0) %>% 
  select_if(not_all_na) %>% 
  replace_na(list('NA' = 0, 'Inf'= 0))

myelin_data_samp2 <- myelin_data_samp2 %>%
  na_if(0) %>% 
  select_if(not_all_na) %>% 
  replace_na(list('NA' = 0, 'Inf'= 0))

#Drop ID columns; drop all columns that sum to 0
thick_data_samp1 <- thick_data_samp1 %>%
  na_if(0) %>% 
  select_if(not_all_na) %>% 
  replace_na(list('NA' = 0, 'Inf'= 0))

thick_data_samp2 <- thick_data_samp2 %>%
  na_if(0) %>% 
  select_if(not_all_na) %>% 
  replace_na(list('NA' = 0, 'Inf'= 0))

```

```{r set_samples, tidy=TRUE}

disc_k2_pheno <- left_join(disc_k2, pheno_data1)
disc_k2_myelin <- left_join(disc_k2, myelin_data_samp1) #[1:30])
disc_k2_thick <- left_join(disc_k2, thick_data_samp1) #[1:30])

repl_k2_pheno <- left_join(repl_k2, pheno_data2)
repl_k2_myelin <- left_join(repl_k2, myelin_data_samp2) #[1:30])
repl_k2_thick <- left_join(repl_k2, thick_data_samp2) #[1:30])

```
## Set group info for Overall Runs

```{r, tidy=TRUE}
#Set original sample
disc_pheno_j <-  disc_k2_pheno %>% 
  select(-c(subid, group)) %>% 
  sapply(as.numeric) %>% 
  t()

disc_myelin_j <- disc_k2_myelin %>% 
  select(-c(subid, group)) %>% 
  t()

disc_thick_j <- disc_k2_thick %>% 
  select(-c(subid, group)) %>% 
  t()

disc_data <- list(disc_pheno_j, disc_myelin_j, disc_thick_j)
raw_data_disc_mat <- rbind(disc_pheno_j, disc_myelin_j, disc_thick_j)

#Set replication sample

repl_pheno_j <- repl_k2_pheno %>% 
  select(-c(subid, group)) %>% 
  sapply(as.numeric) %>% 
  t()

repl_myelin_j <- repl_k2_myelin %>% 
  select(-c(subid, group)) %>% 
  t()

repl_thick_j <- repl_k2_thick %>% 
  select(-c(subid, group)) %>% 
  t()

repl_data <- list(repl_pheno_j, repl_myelin_j, repl_thick_j)
raw_data_repl_mat <- rbind(repl_pheno_j, repl_myelin_j, repl_thick_j)

```

# Run Jive for overall Discovery vs Replication sets
### Run JIVE for Discovery Data

```{r, tidy=TRUE}

## RUN JIVE for Discovery Data
try(cmi_jive_result_disc <- jive(disc_data, conv="default", method='perm'))

#Plot variance explained by individual and joint ranks, and noise
try(cmi_jive_var_disc <- showVarExplained(cmi_jive_result_disc, col = c("#811c4e", "#fdb663", "#37486d")))


(cmi_jive_result_disc$rankA)

showPCA(cmi_jive_result_disc, n_joint = 1, n_indiv = c(1,1,1), 
         Colors = c("red", "blue", "orange"), pch=1)
```

```{r, tidy=TRUE}

#Get Joint Structure
pheno_result_joint_disc <- cmi_jive_result_disc$joint[1] %>% 
  as_tibble(.name_repair = ~"pheno_joint") %>% 
  as.matrix()

myelin_result_joint_disc <- cmi_jive_result_disc$joint[2] %>% 
  as_tibble(.name_repair = ~"myelin_joint")%>% 
  as.matrix()

thick_result_joint_disc <- cmi_jive_result_disc$joint[3] %>% 
  as_tibble(.name_repair = ~"thick_joint") %>% 
  as.matrix()

pheno_result_individual_disc <- cmi_jive_result_disc$individual[1] %>% 
  as_tibble(.name_repair = ~"pheno_individual") %>% 
  as.matrix()

myelin_result_individual_disc <- cmi_jive_result_disc$individual[2] %>% 
  as_tibble(.name_repair = ~"myelin_individual") %>% 
  as.matrix()

thick_result_individual_disc <- cmi_jive_result_disc$individual[3] %>% 
  as_tibble(.name_repair = ~"thick_individual") %>% 
  as.matrix()

pheno_tibble_disc <- rbind(pheno_result_joint_disc, pheno_result_individual_disc)
myelin_tibble_disc <- rbind(myelin_result_joint_disc, myelin_result_individual_disc)
thick_tibble_disc <- rbind(thick_result_joint_disc, thick_result_individual_disc)
all_data_mat_disc<- rbind(pheno_tibble_disc, myelin_tibble_disc, thick_tibble_disc)

spec_data_all_disc <- list(pheno_tibble_disc, myelin_tibble_disc, thick_tibble_disc)
spec_data_joint_disc <- list(pheno_result_joint_disc, myelin_result_joint_disc, thick_result_joint_disc)
spec_data_individ_disc <- list(pheno_result_individual_disc, myelin_result_individual_disc,
                          thick_result_individual_disc)

jive_cluster_disc <- Spectrum(spec_data_individ_disc, maxk=10)

#Dimensionality Reduction using tSNE (t-Distributed Stochastic Neighbor Embedding); good for plotting
disc_rtsne <- Rtsne(t(raw_data_disc_mat),dim=3)

#3D plot the results
(plot3d <- scatter3D(disc_rtsne$Y[,1],disc_rtsne$Y[,2],disc_rtsne$Y[,3], phi = 0, #bty = "g", ex = 2,
          ticktype = "detailed", colvar = jive_cluster_disc$assignments,
          col = gg.col(2), pch=20, cex=2, #type = 'h',
          xlab='Pheno Data (raw values)', ylab='Myelination (raw values)', zlab='Thickness(raw values)', main = "3D JIVE Clustering of Brain & Behav Data (Discovery)"))

```


```{r, tidy=TRUE}

# Create data frame 

x <- data_frame(jive_cluster_disc$assignments) %>% 
  cbind(samp1_ids)
write_csv(x, paste(results, 'Discovery_Data_Cluster_Assignments.csv', sep='/'))

```

```{r, tidy=TRUE}

#3D plot with SNF grouping
(plot3d_disc_snf <- scatter3D(disc_rtsne$Y[,1],disc_rtsne$Y[,2],disc_rtsne$Y[,3], phi = 0, #bty = "g", ex = 2,
          ticktype = "detailed", colvar = disc_k2$group,
          col = jet.col(2), pch=20, cex=2, #type = 'h',
          xlab='Pheno Data (raw values)', ylab='Myelination (raw values)', zlab='Thickness (raw values)', main = "3D SNF Clustering of Brain & Behav Data (Discovery)"))


```






### Run JIVE for Replication Data

```{r, tidy=TRUE}
## RUN JIVE for Replication Data
try(cmi_jive_result_repl <- jive(repl_data, scale = TRUE, conv="default", method='perm'))

#Plot variance explained by individual and joint ranks, and noise
try(cmi_jive_var_repl <- showVarExplained(cmi_jive_result_repl, col = c("#811c4e", "#fdb663", "#37486d")))

#Show PCA grouping
showPCA(cmi_jive_result_repl, n_joint = 1, n_indiv = c(1,1,1), 
         Colors = c("red", "blue", "orange"), pch=1)
```

```{r, tidy=TRUE}

#Get Joint Structure
pheno_result_joint_repl <- cmi_jive_result_repl$joint[1] %>% 
  as_tibble(.name_repair = ~"pheno_joint") %>% 
  as.matrix()

myelin_result_joint_repl <- cmi_jive_result_repl$joint[2] %>% 
  as_tibble(.name_repair = ~"myelin_joint")%>% 
  as.matrix()

thick_result_joint_repl <- cmi_jive_result_repl$joint[3] %>% 
  as_tibble(.name_repair = ~"thick_joint") %>% 
  as.matrix()

pheno_result_individual_repl <- cmi_jive_result_repl$individual[1] %>% 
  as_tibble(.name_repair = ~"pheno_individual") %>% 
  as.matrix()

myelin_result_individual_repl <- cmi_jive_result_repl$individual[2] %>% 
  as_tibble(.name_repair = ~"myelin_individual") %>% 
  as.matrix()

thick_result_individual_repl <- cmi_jive_result_repl$individual[3] %>% 
  as_tibble(.name_repair = ~"thick_individual") %>% 
  as.matrix()

pheno_tibble_repl <- rbind(pheno_result_joint_repl, pheno_result_individual_repl)
myelin_tibble_repl <- rbind(myelin_result_joint_repl, myelin_result_individual_repl)
thick_tibble_repl <- rbind(thick_result_joint_repl, thick_result_individual_repl)
all_data_mat_repl <- rbind(pheno_tibble, myelin_tibble, thick_tibble)

spec_data_all_repl <- list(pheno_tibble_repl, myelin_tibble_repl, thick_tibble_repl)
spec_data_join_replt <- list(pheno_result_joint_repl, myelin_result_joint_repl, thick_result_joint_repl)
spec_data_individ_repl <- list(pheno_result_individual_repl, myelin_result_individual_repl,
                          thick_result_individual_repl)

library(Spectrum)
library(plot3D)

jive_cluster_repl <- Spectrum(spec_data_individ_repl, maxk=10) 

#Dimensionality Reduction using tSNE (t-Distributed Stochastic Neighbor Embedding); good for plotting
repl_rtsne <- Rtsne(t(raw_data_repl_mat),dim=3)

#3D plot the results

(plot3d <- scatter3D(repl_rtsne$Y[,1],repl_rtsne$Y[,2],repl_rtsne$Y[,3], phi = 0, #bty = "g", ex = 2,
          ticktype = "detailed", colvar = jive_cluster_repl$assignments,
          col = gg.col(3), pch=20, cex=2, #type = 'h',
          xlab='Pheno Data (raw values)', ylab='Myelination (raw values)', zlab='Thickness (raw values)', main = "3D JIVE Clustering of Brain & Behav Data (Replication)"))


```

```{r, tidy=TRUE}

# Create data frame 

z <- data_frame(jive_cluster_repl$assignments) %>% 
  cbind(samp2_ids)
write_csv(z, paste(results, 'Replication_Data_Cluster_Assignments.csv', sep='/'))

(plot3d_repl_snf <- scatter3D(repl_rtsne$Y[,1],repl_rtsne$Y[,2],repl_rtsne$Y[,3], phi = 0, #bty = "g", ex = 2,
          ticktype = "detailed", colvar = repl_k2$group,
          col = jet.col(2), pch=20, cex=2, #type = 'h',
          xlab='Pheno Data (raw values)', ylab='Myelination (raw values)', zlab='Thickness (raw values)s', main = "3D JIVE Clustering of Brain & Behav Data (Replication)"))

```

################################################################################################

## Group difference analysis

################################################################################################

```{r, tidy=TRUE}

#Discovery
snf_disc_k2 <- disc_k2
jive_disc_k2 <- jive_cluster_disc$assignments 
both_disc <- cbind(snf_disc_k2, jive_disc_k2) 

(prop_disc_same <- mean(both_disc[["group"]]==both_disc[["jive_disc_k2"]]))

#Replication
snf_repl_k2 <- repl_k2
jive_repl_k2 <- jive_cluster_repl$assignments
both_repl <- cbind(snf_repl_k2, jive_repl_k2) 

(prop_repl_same <- mean(both_repl[["group"]]==both_repl[["jive_repl_k2"]]))

```
