---
title: "CMI_ABCD_JIVE"
author: "Lucinda Sisk"
date: "1/12/2020"
output:
  pdf_document: default
  html_document: default
---

```{r read_in_data, echo=FALSE, include=FALSE, tidy=TRUE}

require(tidyverse)
require(r.jive)
require(dplyr)

results <- '/gpfs/milgram/project/gee_dylan/lms233/CMI_ABCD/Results'

#Read in JIVE data

# pheno_data <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/ABCD_Metrics/final_data/CMI_ABCD_Sample1_clinicalvars.csv', col_names = TRUE)
# myelin_data <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/ABCD_Metrics/CMI_ABCD_Sample1_myelin.csv', col_names = TRUE)
# thick_data <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/ABCD_Metrics/CMI_ABCD_Sample1_thickness.csv', col_names=TRUE)
# corrected_groups <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/ABCD_Metrics/final_data/SNF_subtyping_result_with_statistical_correction_for_pheno.csv', col_names=TRUE)
# uncorrected_groups <- read_csv('/Users/lucindasisk/Box/LS_Folders/CMI_ABCD/ABCD_Metrics/final_data/SNF_subtyping_result_with_statistical_correction_for_pheno.csv', col_names=TRUE)

pheno_data <- read_csv('/gpfs/milgram/project/gee_dylan/lms233/CMI_ABCD/CMI_ABCD_Sample1_clinicalvars.csv', col_names = TRUE)
myelin_data <- read_csv('/gpfs/milgram/project/gee_dylan/lms233/CMI_ABCD/CMI_ABCD_Sample1_myelin.csv', col_names = TRUE)
thick_data <- read_csv('/gpfs/milgram/project/gee_dylan/lms233/CMI_ABCD/CMI_ABCD_Sample1_thickness.csv', col_names=TRUE)
corrected_groups <- read_csv('/gpfs/milgram/project/gee_dylan/lms233/CMI_ABCD/SNF_subtyping_result_with_statistical_correction_for_pheno.csv', col_names=TRUE)
uncorrected_groups <- read_csv('/gpfs/milgram/project/gee_dylan/lms233/CMI_ABCD/SNF_subtyping_result_with_statistical_correction_for_pheno.csv', col_names=TRUE)

```

### Drop empty columns, combine data to ensure same IDs

```{r clean_data, tidy=TRUE}
not_all_na <- function(x) any(!is.na(x))

#Drop ID columns; drop all columns that sum to 0
myelin_data_clean <- myelin_data %>%
  select_if(not_all_na) 

#Drop ID columns; drop all columns that sum to 0
thick_data_clean <- thick_data %>%
  select_if(not_all_na) 

#Add in group info
merged_groups <- full_join(corrected_groups, uncorrected_groups)

#Merge data frames to ensure they are in same order
m1_cor <- left_join(corrected_groups, myelin_data_clean, by='subid')
m2_cor <- full_join(m1_cor, thick_data_clean, by='subid')
m3_cor <- full_join(m2_cor, pheno_data, by=c('subid'='Row'))
brain_df <- m3_cor

#Create groups

group_1_brain <- brain_df %>% 
  filter(Corrected_Group == 1) %>%
  select("zmyelin_set1":"zthickness_set16383")

group_2_brain <- brain_df %>% 
  filter(Corrected_Group == 2) %>%
  select("zmyelin_set1":"zthickness_set16383")

group_3_brain <- brain_df %>% 
  filter(Corrected_Group == 3) %>%
  select("zmyelin_set1":"zthickness_set16383")

group_4_brain <- brain_df %>% 
  filter(Corrected_Group == 4) %>%
  select("zmyelin_set1":"zthickness_set16383")

group_1_pheno <- brain_df %>% 
  filter(Corrected_Group == 1) %>%
  select("meim_p_ss_exp1":"trauma_num1")

group_2_pheno <- brain_df %>% 
  filter(Corrected_Group == 2) %>%
  select("meim_p_ss_exp1":"trauma_num1")

group_3_pheno <- brain_df %>% 
  filter(Corrected_Group == 3) %>%
  select("meim_p_ss_exp1":"trauma_num1")

group_4_pheno <- brain_df %>% 
  filter(Corrected_Group == 4) %>%
  select("meim_p_ss_exp1":"trauma_num1")

```


```{r assign_groups_transpose, tidy=TRUE}
#Select subgroup information

group_1_brain_mat <- t(group_1_brain)
group_1_pheno_mat <- t(group_1_pheno)

group_2_brain_mat <- t(group_2_brain)
group_2_pheno_mat <- t(group_2_pheno)

group_3_brain_mat <- t(group_3_brain)
group_3_pheno_mat <- t(group_3_pheno)

group_4_brain_mat <- t(group_4_brain)
group_4_pheno_mat <- t(group_4_pheno)

```

## Prepare matrices, run jive

* Data requirements: A list of two or more linked data matrices on which to perform the JIVE decomposition. These matrices must have the same column dimension, which is assumed to be common.
```{r create_data_lists, tidy=TRUE}
#Combine measures into list

data_1 <- list(group_1_pheno_mat, group_1_brain_mat)
data_2 <- list(group_2_pheno_mat, group_2_brain_mat)
data_3 <- list(group_3_pheno_mat, group_3_brain_mat)
data_4 <- list(group_4_pheno_mat, group_4_brain_mat)

all_data <- c(data_1, data_2, data_3, data_4)

all_data[1]
```

```{r run_JIVE_data1, tidy=TRUE}
#Run JIVE analysis for GROUP 1

#Estimate JIVE ranks based on permutation testing (best validated)
#Row-orthogonality enforced between the joint and individual estimates and also between each individual estimate.
#Compute ranks
(try(cmi_jive_result <- jive(data_1, scale = FALSE)))

#Get Results
result_joint_rank <- cmi_jive_result$rankJ
result_individ_rank <- cmi_jive_result$rankA

#Plot variance explained by individual and joint ranks, and noise
(try(cmi_jive_var <- showVarExplained(cmi_jive_result, col = c("#811c4e", "#fdb663", "#37486d"))))

#Plot heatmaps of results
(try(cmi_jive_heatmaps <- showHeatmaps(cmi_jive_result, order_by = 0, show_all = TRUE)))

#Plot PCA 
try(cmi_jive_pca <- showPCA(cmi_jive_result, n_joint = result_joint_rank, n_indiv = c(1,1), Colors = c("#811c4e", "#fdb663")))
#No clustering efects apparent

```

```{rrun_JIVE_data2, tidy=TRUE, dpi=50}
#Run JIVE analysis for GROUP 2

#Estimate JIVE ranks based on permutation testing (best validated)
#Row-orthogonality enforced between the joint and individual estimates and also between each individual estimate.
#Compute ranks
(try(cmi_jive_result <- jive(data_2, scale = FALSE)))

#Get Results
result_joint_rank <- cmi_jive_result$rankJ
result_individ_rank <- cmi_jive_result$rankA

#Plot variance explained by individual and joint ranks, and noise
(try(cmi_jive_var <- showVarExplained(cmi_jive_result, col = c("#811c4e", "#fdb663", "#37486d"))))

#Plot heatmaps of results
(try(cmi_jive_heatmaps <- showHeatmaps(cmi_jive_result, order_by = 0, show_all = TRUE)))

#Plot PCA 
try(cmi_jive_pca <- showPCA(cmi_jive_result, n_joint = result_joint_rank, n_indiv = c(1,1), Colors = c("#811c4e", "#fdb663")))
#No clustering efects apparent

```

```{r run_JIVE_data3, tidy=TRUE, dpi=50}
#Run JIVE analysis for GROUP 3

#Estimate JIVE ranks based on permutation testing (best validated)
#Row-orthogonality enforced between the joint and individual estimates and also between each individual estimate.
#Compute ranks
(try(cmi_jive_result <- jive(data_3, scale = FALSE)))

#Get Results
result_joint_rank <- cmi_jive_result$rankJ
result_individ_rank <- cmi_jive_result$rankA

#Plot variance explained by individual and joint ranks, and noise
(try(cmi_jive_var <- showVarExplained(cmi_jive_result, col = c("#811c4e", "#fdb663", "#37486d"))))

#Plot heatmaps of results
(try(cmi_jive_heatmaps <- showHeatmaps(cmi_jive_result, order_by = 0, show_all = TRUE)))

#Plot PCA 
try(cmi_jive_pca <- showPCA(cmi_jive_result, n_joint = result_joint_rank, n_indiv = c(1,1), Colors = c("#811c4e", "#fdb663")))
#No clustering efects apparent

```

```{r run_JIVE_data4, tidy=TRUE, dpi=50}
#Run JIVE analysis for GROUP 4

#Estimate JIVE ranks based on permutation testing (best validated)
#Row-orthogonality enforced between the joint and individual estimates and also between each individual estimate.
#Compute ranks
(try(cmi_jive_result <- jive(data_4, scale = FALSE)))

#Get Results
result_joint_rank <- cmi_jive_result$rankJ
result_individ_rank <- cmi_jive_result$rankA

#Plot variance explained by individual and joint ranks, and noise
(try(cmi_jive_var <- showVarExplained(cmi_jive_result, col = c("#811c4e", "#fdb663", "#37486d"))))

#Plot heatmaps of results
(try(cmi_jive_heatmaps <- showHeatmaps(cmi_jive_result, order_by = 0, show_all = TRUE)))

#Plot PCA 
try(cmi_jive_pca <- showPCA(cmi_jive_result, n_joint = result_joint_rank, n_indiv = c(1,1), Colors = c("#811c4e", "#fdb663")))
#No clustering efects apparent

```

$\\$


```{r, tidy=TRUE}
# ##Save images
# #Save variance images
# png(paste(results, "/CMI_JIVE_VarExplained.png", sep=''),height=300,width=450)
# cmi_jive_var
# dev.off()
# 
# #Save heatmaps
# png(paste(results, "/CMI_JIVE_Heatmaps.png", sep=''),height=465,width=705)
# cmi_jive_heatmaps
# dev.off()
# 
# #Save PCA plots
# png(paste(results, "/CMI_JIVE_PCA_plots.png", sep=''),height=600,width=600)
# cmi_jive_pca
# dev.off()
```




