---
title: "LS_CMI_ABCD_Script_practice"
author: "Lucinda Sisk"
date: "2/4/2020"
output: pdf_document
---

```{r, tidy=TRUE}

require(tidyverse)
require(r.jive)
require(dplyr)

data(SimResults)
data(SimData)

    
```

```{r, tidy=TRUE, dpi=50, fig.retina=1, out.width="30%"}

#Run JIVE analysis for GROUP 3

#Estimate JIVE ranks based on permutation testing (best validated)
#Row-orthogonality enforced between the joint and individual estimates and also between each individual estimate.
#Compute ranks
(try(cmi_jive_result <- jive(SimData, conv=0.05)))

#Get Results

#Plot variance explained by individual and joint ranks, and noise
(try(cmi_jive_var <- showVarExplained(cmi_jive_result, col = c("#811c4e", "#fdb663", "#37486d"))))

#Plot heatmaps of results
(try(cmi_jive_heatmaps <- showHeatmaps(cmi_jive_result, order_by = 0, show_all = TRUE)))

result_joint_rank <- cmi_jive_result$rankJ
result_individ_rank <- cmi_jive_result$rankA#

#Plot PCA 
try(cmi_jive_pca <- showPCA(cmi_jive_result, n_joint = result_joint_rank, n_indiv = c(1,1), Colors = c("#811c4e", "#fdb663")))
#No clustering efects apparent


```
